### ISSUE TITLE
New Task: Reorganize list under "Categories of Marine Life observations" by observing method

### ISSUE THREAD

**Issue by laurabrenskelle** [ioos/marine_life_data_network#106]
### Who is requesting this?

@ioos/marine-life

### What is being requested?

Reorganize the bullets on [this page](https://ioos.github.io/marine_life_data_network/) under "Categories of Marine Life observations" by observing method rather than data type.

### What is the current status quo (i.e., what happens if this does not get done)?

The current bullets are formatted more for observing methods' output data types rather than the method used. This might not be clear for all MLDN users/readers.

### What indicates this is done (i.e., how do we know this is complete)?

Updates have been published to the MLDN GitHub site.

### Provide a description or any other important information.

Include plankton to make it clear that this is a current gap. This involves imagery and optics data types, but may have different workflows for different observing methods.

**Comment by mmckinzie** [comment]
I would add archival tags and multisensor tags to the list as well.

**Comment by MathewBiddle** [comment]
Would those fall under satellite telemetry?

**Comment by mmckinzie** [comment]
Sometime yes and sometime no. Depends on tag type. Often those types of tags need to be recovered to retrieve/download data as they don't have always have the capability to transmit data via the Argos, Cellular or iridium networks

**Comment by laurabrenskelle** [comment]
I would try to keep the categories general. I think it is ok if there are multiple specific kinds/brands of observing methods under one umbrella as long as they can still be binned into these larger categories. One thing I would keep in mind while deciding how granular to be: Are there differences in the high-level workflow for the output data & where it should be shared that would warrant a different data flow diagram?

@MathewBiddle I think I would make "IFCB" something more general because there are other plankton imagery tools that have different names. Maybe label this "Plankton Imaging" instead? That seems to be what we came to for the MBON data mobilization survey.

I'd combine video with imagery "Video/Imagery"? But I think the plankton imaging bin is different enough because these are specific tools that have specific data workflows and repositories.

@mmckinzie I would say that specific types of tags would go under the appropriate satellite or acoustic telemetry label since this list is for marine life observations - any environmental information collected with the occurrence information is a "bonus". To retrieve the data, does the tag ping a satellite to give its location where it can be picked up to download the data from it? Are there vastly different output data types/places these data get shared between the different tag types - to the point that it would warrant different data flow diagrams? My understanding is that there would be different data flows for acoustic and satellite telemetry (especially where & how they get shared), but I don't know if getting more granular in the MLDN documentation is necessary. However, this could definitely be done in some ATN-specific documentation to help that community. I think the MLDN documentation should be the first stop for data managers who don't know what to do with the data they have, and we can link to more detailed documentation in cases where it exists (for example, the NOAA Omics eDNA guide).

**Comment by mmckinzie** [comment]
The general categories for telemetry/ATN should be acoustic, satellite and archival. All tag types can more or less fall under those overarching buckets.

**Comment by MathewBiddle** [comment]
I plan to tackle this today, so standby on a draft for review.

I think @laurabrenskelle hits on a good point wrt data flows. This should be very high level. Is there a significant difference in the high level data flow between archival and satellite tags?

For example, if someone collects data from satellite tags, they should work with ATN to standardize and share their data. ATN then goes into the nuances about manufacturers and other specifics. If someone collects acoustic tag data, they should work with the appropriate OTN node to standardize and share their data. The OTN Node then has further specifics about those data. 

So, from those examples would someone collecting archival tag data work with ATN? Or, is there another place they should be going to standardize and share data?

**Comment by MathewBiddle** [comment]
at the end of the day, I'd like to rework a diagram similar to 
![this](https://ioos.github.io/ncei-archiving-cookbook/DataArchiveDecisionTreeForGoogle-large.png)

**Comment by MathewBiddle** [comment]
Drafted some changes. You can review the draft website at https://mathewbiddle.github.io/marine_life_data_network/#categories-of-marine-life-observations

**Comment by conniekot** [comment]
@MathewBiddle Can you please change this Status = In Progress or Done? I can't do that - thanks!

**Comment by MathewBiddle** [comment]
This is `Done` with this merged PR - https://github.com/ioos/marine_life_data_network/pull/114

See https://ioos.github.io/marine_life_data_network/index.html#categories-of-marine-life-observations

![Image](https://github.com/user-attachments/assets/49bdad2f-7315-4a92-84dd-d01ce4e35416)
