### ISSUE TITLE
New Task: Improve Approach for Visualizing and Binning ATN Data

### ISSUE THREAD

**Issue by iwensu0313** [ioos/marine_life_data_network#118]
### Who is requesting this?

ATN DAC

### What is being requested?

Particularly for very large ATN data projects (example: [Northern Elephant Seal](https://portal.atn.ioos.us/#metadata/edc4b2d0-b90d-484b-86da-e1e4212409f6/project)), there are issues with overbinning as identified by the ATN DAC coordinator.

The request is to address the issue so that the data are not being overbinned in the visualization. 

### What is the current status quo (i.e., what happens if this does not get done)?

When looking at the past month or past week for example you might only see 3 dots on the map instead of 10. How many bins are appropriate are defined by ATN DAC coordinator and Axiom together.

### What indicates this is done (i.e., how do we know this is complete)?

Some back and forth with the ATN DAC coordinator is required to ensure the level of binning is appropriate with iterative improvements.

**Comment by iwensu0313** [comment]
A short-term, front-end adjustment was made (in a staging portal environment) to improve the visualization/binning, but utilizing the new binning service (binninator) will make it easier to adapt the binning approach for datasets long-term. 

The results of the short-term approach still needs to be reviewed with the ATN DAC Coordinator.

**Comment by MathewBiddle** [comment]
Related to https://github.com/ioos/marine_life_data_network/issues/50 ? Do we need both?

**Comment by iwensu0313** [comment]
It does look related! I'll merge the info I was planning to add here to #50 and "Close as not planned"

**Comment by MathewBiddle** [comment]
removed from board as it's a duplicate
