### ISSUE TITLE
What are we looking for with timeline?

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/marine_life_data_network#12]
For our issue template, we ask the question about timeline. Is this the IOOS timeline? desired timeline from requestor? Expected completion date? Desired completion date? 

We should further define this.

https://github.com/ioos/marine_life_data_network/blob/813aad59765c94a153c66b56f8dec05d259b0c86/.github/ISSUE_TEMPLATE/new_task.yml?plain=1#L20

**Comment by laurabrenskelle** [comment]
I updated the GitHub issue template. Is this question better?

"What is the requested deadline for the completion of this task?"

**Comment by MathewBiddle** [comment]
Maybe "What is the requested deadline and why that deadline?" 

If it's a short turn around topic, I'd like to know why.

**Comment by laurabrenskelle** [comment]
I made that change in the issue template.
