### ISSUE TITLE
New Task: Create a document summarizing years 1-2 progress.

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/marine_life_data_network#22]
### Who is requesting this?

@ioos/marine-life

### What is being requested?

Create documents summarizing Marine Life developments from Dec 2022 - Nov 2024.

### What is the requested deadline and why?

2024-11-30

### What is the current status quo (i.e., what happens if this does not get done)?

IOOS Marine Life Team will not have a full picture of the work completed and where to take our efforts in the future.

### What indicates this is done (i.e., how do we know this is complete)?

- [x] Document for Marine Life SOW from Dec 2022 - Nov 2024 
- [x] Document for DTAG/Open Source Documentation SOW from July 2023 - June 2024

### Provide a description or any other important information.

It should be succinct enough, but not too detailed, to give the IOOS Office a perspective of the activities accomplished and where to focus efforts for future support. Documents should include hyperlinks to resultant work and brief summaries of work performed. If work is not complete, a brief summary of what is needed to complete the work.

**Comment by MathewBiddle** [comment]
Documents should include hyperlinks to resultant work and brief summaries of work performed. If work is not complete, a brief summary of what is needed to complete the work.

**Comment by MathewBiddle** [comment]
@mmckinzie @conniekot @GabCan please add anything relevant here.

**Comment by conniekot** [comment]
> Documents should include hyperlinks to resultant work and brief summaries of work performed. If work is not complete, a brief summary of what is needed to complete the work.

Added this info to above description

**Comment by MathewBiddle** [comment]
I've updated the description to be a little more specific.

**Comment by MathewBiddle** [comment]
IMO this issue is complete. @iwensu0313 provided a summary of the work done via email. Thanks!!

**Comment by MathewBiddle** [comment]
As this is complete, moving to `Done`.
