### ISSUE TITLE
New Task: Automate ingestion of SPOT style tags to ADR

### ISSUE THREAD

**Issue by laurabrenskelle** [ioos/marine_life_data_network#24]
### Who is requesting this?

@ioos/marine-life 

### What is being requested?

Automate the ingestion of SPOT style tags to the ATN Project Registration application (ADR). This includes WC SPOT and SMRU SRDL tags.

### What is the requested deadline and why?

2024-07-01

### What is the current status quo (i.e., what happens if this does not get done)?

Ingestion of these tag styles may require extra work to be manually ingested and this will be more time consuming.

### What indicates this is done (i.e., how do we know this is complete)?

- [ ] The source code is published on GitHub at [ioos/ioos-atn-data](https://github.com/ioos/ioos-atn-data/) and well documented, or other appropriate repository.
- [x] Data from these tags is being automatically ingested into ADR and the data are correct.

### Provide a description or any other important information.

cc @mmckinzie

**Comment by laurabrenskelle** [comment]
@MathewBiddle @mmckinzie I am trying to fill out the issues for automated ingestion of different tag types, but I am not sure what an appropriate timeline for these might be. Please advise & we can update that in the issues.

**Comment by mmckinzie** [comment]
@laurabrenskelle @MathewBiddle Thanks for attempting to populated issue tickets related to ATN DAC tasking. I hope to be able to spend some time tomorrow (Friday) and early next week to review and edit tickets as needed as there are quite a few details that need to be updated and documented correctly under each individual issue/task. 

For example, these tag/data types are already successfully integrated into the DAC including the ADR. These data are being auto-ingested, rarely if ever manually uploaded/ingested. The original task as laid out in our SOW/Workplan as well as similar ingestion tasks for other tag types are about more than just ensuring these data are linked to the ADR. We have also never discuss posting the source code with Axiom so we should verify what an appropriate due date would be for them to accomplish this task, July 1 seems unlikely.

**Comment by laurabrenskelle** [comment]
@mmckinzie That sounds good. Honestly the timeline and the "what is done" for these tasks was me spitballing because I do not have the background knowledge on what the tasks actually are. We can make any necessary changes to these issues so they make sense.

**Comment by MathewBiddle** [comment]
Found a note stating:
* WC SPOT
* SMRU SRDL

I have no clue what that means but I want to be sure we don't loose information.

**Comment by mmckinzie** [comment]
This task can be marked as complete. We may need to create a new issue if we expand services to harvest/auto-ingest data from additional tag manufacturers and for similar Argos based satellite tags, but this process is working as expected for Wildlife Computers (WC) and Sea Mammal Research Unit (SMRU) Smart Position and Temperature (SPOT) tags and Satellite-Relay Data Loggers (SRDL).

**Comment by MathewBiddle** [comment]
Let's leave this open and close it during our Friday meeting. I'd like to see a link or some documentation describing what was done to close this issue. Is there a new button on the ATN Project Registration application (ADR) for SPOT?

**Comment by mmckinzie** [comment]
No ' button' is required. Data are able to be auto ingested from manufacturer, new data harvested every 2 hrs, QC protocols and/or aniMotum run every 4 hrs for near r/t data feeds and portal visualizations updated every 6 hrs for near r/t data feeds, data files successfully linked to ADR via download tab for all deployments linked to portal and files are updated every 4 hrs for near r/t data feeds. Data from completed and/or historic deployments also being successful harvested from manufacturer, linked to portal and ADR, QC and aniMotum also run. Process is working as expected.

**Comment by lmshowalter3** [comment]
Add screenshot of the portal to document this task as done. @lmshowalter3
