### ISSUE TITLE
New Task: Automate ingestion of PAT tags to ADR

### ISSUE THREAD

**Issue by laurabrenskelle** [ioos/marine_life_data_network#25]
### Who is requesting this?

@ioos/marine-life

### What is being requested?

Automate the ingestion of PAT style tags to the ATN Project Registration application (ADR). This includes WC PAT, miniPAT, and MK10s (i.e., GPE3 files).

### What is the requested deadline and why?

2024-07-01

### What is the current status quo (i.e., what happens if this does not get done)?

Ingestion of these tag styles may require extra work to be manually ingested and this will be more time consuming.

### What indicates this is done (i.e., how do we know this is complete)?

- [ ] The source code is published on GitHub at [ioos/ioos-atn-data](https://github.com/ioos/ioos-atn-data/) and well documented, or other appropriate repository.
- [ ] Data from these tags is being automatically ingested into ADR and the data are correct.

### Provide a description or any other important information.

cc @mmckinzie

**Comment by mmckinzie** [comment]
This task can also be marked as complete. A new issue ticket can be created if we begin auto ingesting pop-up archival transmitting (PAT, also known as PSAT) tag data from additional manufacturers beyond Wildlife Computers.

**Comment by MathewBiddle** [comment]
Let's leave this open and close it during our Friday meeting. I'd like to see a link or some documentation describing what was done to close this issue. Is there a new button on the ATN Project Registration application (ADR) for PAT?

**Comment by mmckinzie** [comment]
Data files successfully harvested from Wildlife Computers, GPE3 files are being properly visualized in portal and data files link to download tab in ADR.
