### ISSUE TITLE
New Task: Automate ingestion of GPS tags to ADR

### ISSUE THREAD

**Issue by laurabrenskelle** [ioos/marine_life_data_network#26]
### Who is requesting this?

@ioos/marine-life

### What is being requested?

Automate the ingestion of GPS style tags to the ATN Project Registration application (ADR). This includes SPOT-F, SPLASH-F, SPLASH10-F, SMRU GPS SRDL, SMRU GPS (GSM).

### What is the requested deadline and why?

2024-07-01

### What is the current status quo (i.e., what happens if this does not get done)?

Ingestion of these tag styles may require extra work to be manually ingested and this will be more time consuming.

### What indicates this is done (i.e., how do we know this is complete)?

- [ ] The source code is published on GitHub at [ioos/ioos-atn-data](https://github.com/ioos/ioos-atn-data/) and well documented, or other appropriate repository.
- [x] Data from these tags is being automatically ingested into ADR and the data are correct.

### Provide a description or any other important information.

cc @mmckinzie

**Comment by mmckinzie** [comment]
This task is complete. We are successfully auto-ingesting data from relevant tag types into the DAC.

**Comment by MathewBiddle** [comment]
Let's leave this open and close it during our Friday meeting. I'd like to see a link or some documentation describing what was done to close this issue. Is there a new button on the ATN Project Registration application (ADR) for GPS?

**Comment by mmckinzie** [comment]
Again, no button required. Same comments as those related to SPOT tags in issue #24
