### ISSUE TITLE
New Task: Automate ingestion of CTD and temperature only profiling tags to ADR

### ISSUE THREAD

**Issue by laurabrenskelle** [ioos/marine_life_data_network#27]
### Who is requesting this?

@ioos/marine-life

### What is being requested?

Automate the ingestion of CTD/CTD-F and temperature only profiling tags to the ATN Project Registration application (ADR). This includes WC SCOUT, WC SPLASH10, SPLASH10-F, SMRU CTD-F, and SMRU CTD GPS.

### What is the requested deadline and why?

2024-07-01

### What is the current status quo (i.e., what happens if this does not get done)?

Ingestion of these tag styles may require extra work to be manually ingested and this will be more time consuming.

### What indicates this is done (i.e., how do we know this is complete)?

- [ ] The source code is published on GitHub at [ioos/ioos-atn-data](https://github.com/ioos/ioos-atn-data/) and well documented, or other appropriate repository.
- [x] Data from these tags is being automatically ingested into ADR and the data are correct.

### Provide a description or any other important information.

cc @mmckinzie

**Comment by mmckinzie** [comment]
This task can be marked as complete. We are successfully auto ingesting data from WC and SMRU profiling tags into the DAC. Eventually a new issue specific to Wildlife Computers tags will need to be created to ensure we're receiving and integrating updated file formats that include matched locations, but these updated data files are not yet available from WC. New issue will also have to include tasking to convert the updated Profile of Depth and Temperature (PDT) files to BUFR messages and serve these data to the GTS as well as ensure profile data are being properly visualized in portal along with trajectory files (location.csv or x-location.csv) similar to SMRU CTD tags. But this work cannot be started until we have accessed to the updated file formats with matched profile locations.

**Comment by MathewBiddle** [comment]
Thanks for providing this update. 

> We are successfully auto ingesting data from WC and SMRU profiling tags into the DAC.

Is this documented somewhere publicly or added to the ADR? 

The rest of your comment should be added as a new issue and put in the backlog where we can evaluate when to work on it:
> Eventually a new issue specific to Wildlife Computers tags will need to be created to ensure we're receiving and integrating updated file formats that include matched locations, but these updated data files are not yet available from WC. New issue will also have to include tasking to convert the updated Profile of Depth and Temperature (PDT) files to BUFR messages and serve these data to the GTS as well as ensure profile data are being properly visualized in portal along with trajectory files (location.csv or x-location.csv) similar to SMRU CTD tags. But this work cannot be started until we have accessed to the updated file formats with matched profile locations.
