### ISSUE TITLE
[New Task]: Create IOOS org GitHub Team for IOOS Marine Life

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/marine_life_data_network#3]
### Who is requesting this?

@mathewbiddle

### What is being requested?

The creation of a team in the IOOS GitHub organization to make it easier to manage communications and permissions for managing IOOS Marine Life repository and future activities.

### What is the timeline for the completion of this task?

2024-04-15

### Provide a description or any other important information.

We should consult with @mwengren on the use of GitHub teams in the IOOS org and if this is an appropriate use of them.

**Comment by MathewBiddle** [comment]
people it should include:
* @MathewBiddle 
* @laurabrenskelle 
* @GabCan 
* @mmckinzie
* Axiom folks...

**Comment by MathewBiddle** [comment]
The only way you can assign people an issue is if they have commented on an issue, have write permissions, and read permissions.

https://docs.github.com/en/issues/tracking-your-work-with-issues/assigning-issues-and-pull-requests-to-other-github-users#about-issue-and-pull-request-assignees

I think using a team would allow broader use of the `assignees` function.

**Comment by MathewBiddle** [comment]
created @ioos/marine-life

**Comment by laurabrenskelle** [comment]
We need to add Lauren Showalter @lmshowalter3, Chris Turner @Iamchrisser, and Ian Gill @gilltron .
