### ISSUE TITLE
change IOOS Core Variables related to bio to the BioEco list

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/marine_life_data_network#31]
From @GabCan: IOOS and IOOC formally adopted the BioEco list, so we should use that.

Biology and Ecosystem terms from https://goosocean.org/what-we-do/framework/essential-ocean-variables/

https://github.com/ioos/marine_life_data_network/blob/ae2cd659ea8a3484a4be8f6bbc2109c660e9d268/README.md?plain=1#L23-L46

**Comment by MathewBiddle** [comment]
`ocean color` is a cross-panel EOV, similar to `ocean sound`.

**Comment by laurabrenskelle** [comment]
Just made this update. https://github.com/ioos/marine_life_data_network/commit/ab8052c623e69808d18e4f4e20ac356b6fba1e67
