### ISSUE TITLE
New Task: Link "Feedback" button to GitHub issue creation

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/marine_life_data_network#40]
### Who is requesting this?

@ioos/marine-life

### What is being requested?

When someone uses the Feedback button on the MBON and ATN portal it creates a message to portal managers. Can that message be sent to this GitHub repository as an issue?

### What is the current status quo (i.e., what happens if this does not get done)?

wont be linked between portal issues and github issues.

### What indicates this is done (i.e., how do we know this is complete)?

- [ ] link the two together

### Provide a description or any other important information.

cc @conniekot

**Comment by lmshowalter3** [comment]
Ticket created in our Jira to set up

**Comment by lmshowalter3** [comment]
At this time we will not automate the feedback button to populate GitHub. If we get feedback that warrants a ticket in this system we will discuss and add it manually.
