### ISSUE TITLE
New Task: Create a service to manage NCEI identifiers in the ADR. 

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/marine_life_data_network#43]
### Who is requesting this?

@ioos/marine-life

### What is being requested?

Create a service to manage NCEI identifiers in the ADR. 

### What is the current status quo (i.e., what happens if this does not get done)?

There will be a lack of clarity as to which tags have been archived at NCEI. This facilitates accessibility as ATN can link directly to the Archived dataset from various access points.

### What indicates this is done (i.e., how do we know this is complete)?

- [x] service is built
- [x] For an archived dataset, identifiers are available in the ADR
- [ ] NCEI identifiers made available in the portal??

### Provide a description or any other important information.

_not quite sure what a "service" is in this context. Will need more details._

**Comment by laurabrenskelle** [comment]
This seems related enough to add here, but what is being used for `dwc:occurrenceID` for ATN data uploaded to OBIS? Seems like keeping track of the identifiers used across ATN-OBIS-NCEI in one resource would be ideal.

**Comment by MathewBiddle** [comment]
We haven't uploaded anything yet (https://github.com/ioos/bio_data_guide/issues/145) but the current workflow builds occurrenceIDs following:

https://github.com/ioos/bio_data_guide/blob/ee309a1418b570f956f2e54ca8dad9e870925f78/datasets/atn_satellite_telemetry/atn_satellite_telemetry_netCDF2DwC.Rmd#L106

https://github.com/ioos/bio_data_guide/blob/ee309a1418b570f956f2e54ca8dad9e870925f78/datasets/atn_satellite_telemetry/atn_satellite_telemetry_netCDF2DwC.Rmd#L190C8-L190C109

`time`_`depth`_`animal common name`

example: `2009-09-23T00:00:00Z_0_great_white_shark`

We should probably include `atn` or something like that to clarify it's from ATN.

**Comment by mmckinzie** [comment]
DOI, DOI subset(?) and NCEI accession number fields have already been added to the ADR satellite metadata template, so a place exists for this information to be stored. However, these fields will need to be manually populated as datasets are released to DataONE, NCEI or other (OBIS??). I not sure if there is any way to automate adding these identifiers to each individual deployment as data are released.  

A running list of all ATN datasets, associated citations and DOIs released to DataONE is available under the IOOS ATN Campaign [Archives](https://researchworkspace.com/campaign/4987450/ioos-atn-campaign/archives) tab in the Research Workspace.  Also, an 'Archived Data' tag has been added to all projects in portal with publicly accessible data to facilitate querying public data from ATN portal catalog.

**Comment by mmckinzie** [comment]
What is or should be used as the dwc:occurrenceID for ATN datasets seems like a separate and unrelated issue this this specific task.  The related task would be whether or not to add a field to the satellite telemetry metadata specification template in the ADR to house this id along with DOI and NCEI accession number, not what form should this id take. 

For the dwc occurrence ids, it may be better to follow the same format as we're using with NCEI to label individual deployments data files (i.e., atn_ptt id_animal-common-name_trajectory_deployment start date-deployment end date, e.g., atn_45866_great-white-shark_trajectory_20090923-20091123)

**Comment by MathewBiddle** [comment]
Agreed. The `dwc:occurrenceID` discussion should be had at https://github.com/ioos/bio_data_guide/issues/145. Nothing for that process is set in stone yet, so we can discuss the appropriate approach over there.

The place for these identifiers has been created. That's fantastic! 

In the description above, it's mentioned that a **service** is built. Is the service simply the place to put this information (ie. what's been done already)? Or, is it some sort of mapping table and automated functions to collect, manage and populate this information in the metadata record?

**Comment by mmckinzie** [comment]
My interpretation is that yes, the 'service' was simply to create a place to put this information, i.e., add appropriate fields to the metadata template in the ADR. Populating these fields would be a manual process and part of my workflow. We have not discussed automating this functionality and I'm not even sure it that is feasible. 

We will still need to decide if it also makes sense to track an analogous DwC or OBIS identifier and add an appropriate field to the template in ADR.

**Comment by lmshowalter3** [comment]
Is considered Done when we can add a screenshot of what this looks like in the ATN portal

**Comment by mmckinzie** [comment]
![Image](https://github.com/user-attachments/assets/9cbfeb48-e7f5-4ada-9b1f-f13fdf623186)

**Comment by MathewBiddle** [comment]
Awesome stuff! 

The last task is related to https://github.com/ioos/marine_life_data_network/issues/33. It would be worth investigating the amount of work needed to accomplish the activity, but lets discuss that over there.

> NCEI identifiers made available in the portal??

Closing this now. Will move to done during our next tag up.
