### ISSUE TITLE
New Task: Meet BUFR requirements

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/marine_life_data_network#46]
### What is being requested?

Modify BUFR encoded packages, implement new tables or sequences as needed, based on WMO ID approach and feedback from validation tests. 

- Respond to any changes or updates to the template based on revised WMO/WIGOS IDs for animal-borne sensors. 
- Implement updated QC protocol, remove hardcoded ‘0’ and add appropriate GTSPP QC flags to BUFR messages based on QARTOD flags

### What is the current status quo (i.e., what happens if this does not get done)?

If data do not meet requirements, than data will not be sent to the GTS.

### What indicates this is done (i.e., how do we know this is complete)?

- [ ] BUFR output is aligned within two months of the most recent table release.

### Provide a description or any other important information.

_Is there an update cycle for BUFR that we need to monitor? If so, the indication of done is dependent on that update cycle. I put some loose terms in there now._

**Comment by MathewBiddle** [comment]
From Trello:
> 6.2.1 Respond to any changes or updates to the template based on revised WMO/WIGOS IDs for animal-borne sensors. This task is in response to the issuance of non-validated IDs in 2022, hence a temporary solution was implemented until the WMO next convenes to approve a modified ID sequence.

**Comment by mmckinzie** [comment]
I think it is fine to keep this task open in case future modifications or updates are required to our BUFR tables but task 6.2.1 and 6.3.1 in Trello are complete. The non-validated ID issue was resolved, BUFR table (TM315023) was updated (v.39) and approved by WMO and included in WMO manual (Nov 2022). Related task 6.3.1 has also been completed. NDBC implemented new decoders to handle updated v.39 BUFR tables in Feb 2023. BUFR messages are being successfully generated in near r/t (every 6 hrs) and sent to NDBC for insertion onto the GTS. 

We have not yet updated the QC protocols to remove hard coded '0' (unqualified) and add appropriate GTSPP QC flags to BUFR messages based on QARTOD roll-up flags.

**Comment by MathewBiddle** [comment]
Awesome! Thanks, Meg. Can you create a new issue (or reference in an existing issue) for:
> We have not yet updated the QC protocols to remove hard coded '0' (unqualified) and add appropriate GTSPP QC flags to BUFR messages based on QARTOD roll-up flags.

I think this issue can be closed, and when new BUFR tables are released we can create new issues for the changes that need to be made. How does that sound? Eg. "Align to BUFR table (TM31024)" or whatever the next table is.

**Comment by mmckinzie** [comment]
Yes, we can make a new issue related to updating the BUFR messages QC flags.
