### ISSUE TITLE
New Task: Make modified Argo QARTOD code available

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/marine_life_data_network#47]
### What is being requested?

Make modified Argo QARTOD code available as a Jupyter notebook and make ATN specific use documentation available online, clearly illustrating how the Argo code was modified for use by the ATN DAC. 

### What is the current status quo (i.e., what happens if this does not get done)?

Unclear implementation of QARTOD

### What indicates this is done (i.e., how do we know this is complete)?

- [ ] documentation/jupyter notebook is released
- [ ] update appropriate documentation at https://github.com/ioos/ioos_qc
- [ ] announcement sent through IOOS Eyes on the Ocean.

### Provide a description or any other important information.

_I don't know what "Argo QARTOD" means. We need more description for what is actually being requested here._

xref:
* https://github.com/ioos/marine_life_data_network/issues/14

**Comment by MathewBiddle** [comment]
xref:
* https://github.com/ioos/marine_life_data_network/issues/73
* https://github.com/ioos/marine_life_data_network/issues/14

**Comment by mmckinzie** [comment]
Ian Jonsen is working on developing/updating IMOS near r/t QC protocols for animal borne profile data and corresponding trajectory files. This work is part of a GOOS Bio-Eco panel pilot project with AniBOS to serve behavioral data to OBIS/GBIF. Jon Pye will also be helping with this effort. Work to begin week of July 15th, 2024. This work will likely utilize elements of the [remora](https://github.com/ocean-tracking-network/remora/) package and OTN DwC templates/OBIS thematic node.  This effort will be discussed at our upcoming AniBOS data committee meeting later this month. 

I'll be curious to see how these IMOS/OTN protocols and QC procedures differ from what the ATN DAC is presently doing using QARTOD. 

These new r/t QC tests will be distinct and differ from existing [MEOP](https://www.[meop.net/database/](https://www.meop.net/database/)) protocols used to develop delay-mode data products, available here: https://osmc.noaa.gov/erddap/tabledap/MEOP_profiles.html

**Comment by MathewBiddle** [comment]
@mmckinzie I assume this is a duplicate of https://github.com/ioos/marine_life_data_network/issues/14 ?

**Comment by mmckinzie** [comment]
@MathewBiddle Yes, I think issue #14 and #47 are more or less capturing the same task or are at least related. The main difference is that this issue mentions generating and releasing a Jupyter notebook in addition to making specific documentation available online as well as sending a notice to community via the Eyes on the Oceans once complete. Issues could possibly be merged.

**Comment by MathewBiddle** [comment]
I didn't want to move this card to `Done` as it really isn't done, but a duplicate of existing issues. Instead, I removed the status, setting it to `No Status`. This way it doesn't show up in the issues we are looking at for in progress/next activities.

We can discuss this at one of the monthlies if folks have questions.

**Comment by MathewBiddle** [comment]
removed from project board
