### ISSUE TITLE
[New Task]: add default documentation to this repo 

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/marine_life_data_network#6]
### Who is requesting this?

@mathewbiddle

### What is being requested?

To encourage participation and/or simply document how this repository functions, I recommend adding a few standard documentation pieces to this repository.

For more information on each of the below items, see https://opensource.guide/starting-a-project/#launching-your-own-open-source-project

- [x] license
- [x] update readme with a little more context (answering some questions such as; What does this project do? Why is this project useful? How do I get started? Where can I get more help, if I need it?)
- [x] contributing guidelines
- [x] #55

### What is the timeline for the completion of this task?

~2 weeks

### Provide a description or any other important information.

@laurabrenskelle we don't need to go overboard, but we should have some boilerplate info in this repository to start with.

**Comment by laurabrenskelle** [comment]
Started draft of contributing guide #39

**Comment by laurabrenskelle** [comment]
https://github.com/ioos/marine_life_data_network/commit/7070299c5badd7d75bce9f4263b0d84436ef9151 Updated readme to provide a little more information listed in the second bullet.

**Comment by laurabrenskelle** [comment]
How do we feel about using a pre-existing Code of Conduct that is used by other open source GH communities?

Two examples:
- [Contributor Covenant](https://www.contributor-covenant.org)
- [Citizen Code of Conduct](https://web.archive.org/web/20200330154000/http://citizencodeofconduct.org/)

I think I lean towards the first one, but we can also write our own from scratch if that might be more fitting. They do both require some sort of reporting mechanism in the case of violations so we will need to discuss where those should be sent before we go live with a Code of Conduct in the repo.

**Comment by MathewBiddle** [comment]
https://github.com/ioos/.github/issues/10

**Comment by laurabrenskelle** [comment]
The IOOS GitHub Code of Conduct was merged, and I added links to that Code of Conduct to the readme and contributing guides so I think we can mark this ticket closed!
