### ISSUE TITLE
New Task: Present at the 3rd National Workshop on Marine eDNA

### ISSUE THREAD

**Issue by laurabrenskelle** [ioos/marine_life_data_network#63]
### Who is requesting this?

@ioos/marine-life

### What is being requested?

@MathewBiddle will be presenting about the mobilization of eDNA into Darwin Core and shared via OBIS at the 3rd National Workshop on Marine eDNA at the Johns Hopkins Applied Physics Laboratory on June 3-5, 2024.

### What is the requested deadline and why?

2024-06-05 - This is the end date of the event.

### What is the current status quo (i.e., what happens if this does not get done)?

eDNA practitioners who attend this workshop may be unaware that their data can be expressed in Darwin Core and therefore may not share their data to OBIS and GBIF.

### What indicates this is done (i.e., how do we know this is complete)?

The presentation is complete.

### Provide a description or any other important information.

Will there be a recording available afterward? That may be useful to link here.

**Comment by MathewBiddle** [comment]
Presentation was executed on 6/4/2024. Slides have been assigned a DOI and published on Zenodo https://zenodo.org/doi/10.5281/zenodo.11464530

doi: 10.5281/zenodo.11464530

**Comment by MathewBiddle** [comment]
@sformel-usgs was an immense help in building the slides and during the workshop. Thanks!
