### ISSUE TITLE
New Task: Attend OTN International Data Management Committee meeting

### ISSUE THREAD

**Issue by laurabrenskelle** [ioos/marine_life_data_network#64]
### Who is requesting this?

@ioos/marine-life

### What is being requested?

Engage with the Ocean Tracking Network (OTN) International Data Management Committee at their annual meeting.

### What is the requested deadline and why?

2024-09-25

### What is the current status quo (i.e., what happens if this does not get done)?

IOOS Marine Life and the ATN may not be represented at this committee meeting if we do not have an representative in attendance.

### What indicates this is done (i.e., how do we know this is complete)?

An IOOS Marine Life representative attended the meeting and shares out any outcomes from the meeting with the IOOS Marine Life community.

### Provide a description or any other important information.

@MathewBiddle sent an email to determine who the appropriate attendee for this event should be.

**Comment by MathewBiddle** [comment]
I have my passport and am coordinating with OTN on travel arrangements.

**Comment by MathewBiddle** [comment]
@mmckinzie @conniekot I have been requested to present the following during the IDMC meeting at the end of September.

A 5-minute update (maximum 3 slides). During this update, please cover key items related to your organization, within the following three themes:
* Background about who you are and your organization
* Key accomplishments
* Future direction and challenges

I will be asking for your support with building the content for these slides. Expect more next week.

**Comment by MathewBiddle** [comment]
@conniekot @mmckinzie I started a slide deck for the IDMC next week. Please add content to Slide 4 on **Future Direction and Challenges** by Friday (09/20). You should both have access to the slide deck. https://docs.google.com/presentation/d/1iWvuMgGdMLqKF7sJ2BUdY8dS98xJ9J7omrokOQ5AVyo/edit#slide=id.g300b339d6ef_0_1

**Comment by mmckinzie** [comment]
@MathewBiddle I added an updated slide (#3) with current DAC stats and figure as the one in your presentation is a bit outdated, with some additional notes copied from my recent SG-18 update. That full slide deck is available [here](https://docs.google.com/presentation/d/1iKTtzg3bv8aqunpiutYpRX5ufoqdr4q4gq6yc66ePAk/edit?usp=sharing). 

I also added a few bullets to slide 4 regarding future directions and challenges. Edit or revise as needed.

**Comment by MathewBiddle** [comment]
@mmckinzie Thank you for the support during this meeting and in prepping the slide deck. This activity is complete.

**Comment by MathewBiddle** [comment]
For reference, 

#107 was inspired from conversations at this IDMC.
and
there was general interest at IDMC about https://ioos.github.io/ioos-atn-data/atn-sat-telem-specification-v1-0.html which has been subsequently shared with the committee.

**Comment by MathewBiddle** [comment]
Yup. Went there, did some stuff. See comments above. This is `Done`.
