### ISSUE TITLE
New Task: Review Marine Life Data Network Trello cards and migrate missing content here

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/marine_life_data_network#67]
### Who is requesting this?

@mathewbiddle

### What is being requested?

We have a Marine Life Data Network Trello board. The cards within that board should be transferred here so we have a one stop shop of activities.

### What is the requested deadline and why?

2024-06-01

### What is the current status quo (i.e., what happens if this does not get done)?

The team will be working from two separate places and confusion will arise.

### What indicates this is done (i.e., how do we know this is complete)?

- [ ] All cards on the Trello board will be closed and referenced as issues in this repository. 

### Provide a description or any other important information.

I am not providing a direct link to the Trello board to limit confusion.

**Comment by laurabrenskelle** [comment]
All of the ATN and MBON Trello cards have been carried over into GitHub issues. For the ones in the column "Marine Life: To Do" in Trello, I wasn't sure if we want to carry over the tasks labeled 4.3.x? And what about 8.7 and 8.8? Is consolidating the ATN and MBON portals into a Marine Life portal still the plan?
