### ISSUE TITLE
New Task: Identify AphiaIDs that align with groups in bio/eco variables

### ISSUE THREAD

**Issue by laurabrenskelle** [ioos/marine_life_data_network#70]
### Who is requesting this?

@ioos/marine-life

### What is being requested?

Identify AphiaIDs that align with the taxonomic groups (if possible) listed in the [bio/eco variables](https://goosocean.org/what-we-do/framework/essential-ocean-variables/) so data can be appropriately filtered to include all necessary taxa.

### What is the current status quo (i.e., what happens if this does not get done)?

Some of these variable names are taxonomically ambiguous so if the GOOS and U.S. IOOS community can agree on taxonomic definitions of the scope of these variables, that would help with further defining these variables and doing analyses.

### What indicates this is done (i.e., how do we know this is complete)?

We will add a finalized list of AphiaIDs for the variables to the readme. These definitions are open for community discussion, and changes can be made if taxa are included or excluded inappropriately.

### Provide a description or any other important information.

I will be doing this with a global scope, with the understanding that some taxa do not occur in the U.S. coastal region. A global definition of what these groups are seems most appropriate and usable by the community, as data can be filtered spatially.

**Comment by laurabrenskelle** [comment]
So far, these are the groups I have defined:

**Marine Mammals**
- Pinnipedia - [urn:lsid:marinespecies.org:taxname:148736](https://www.marinespecies.org/aphia.php?p=taxdetails&id=148736)
- Cetacea - [urn:lsid:marinespecies.org:taxname:2688](https://www.marinespecies.org/aphia.php?p=taxdetails&id=2688)
- Sirenia - [urn:lsid:marinespecies.org:taxname:159502](https://www.marinespecies.org/aphia.php?p=taxdetails&id=159502)
- Otters - _Enhydra_ [urn:lsid:marinespecies.org:taxname:242597](https://www.marinespecies.org/aphia.php?p=taxdetails&id=242597); _Lontra felina_ [urn:lsid:marinespecies.org:taxname:343992](https://www.marinespecies.org/aphia.php?p=taxdetails&id=343992); _Lontra canadensis_ [urn:lsid:marinespecies.org:taxname:159017](https://www.marinespecies.org/aphia.php?p=taxdetails&id=159017)
-- A note about _Lontra felina_ - I know WoRMS says this is not an accepted name, but I believe that is inaccurate and I did reach out to them about fixing this.
- Polar bear - _Ursus maritimus_; [urn:lsid:marinespecies.org:taxname:137085](https://www.marinespecies.org/aphia.php?p=taxdetails&id=137085)

**Seagrasses**
- Posidoniaceae - [urn:lsid:marinespecies.org:taxname:143769](https://www.marinespecies.org/aphia.php?p=taxdetails&id=143769)
- Zosteraceae - [urn:lsid:marinespecies.org:taxname:143770](https://www.marinespecies.org/aphia.php?p=taxdetails&id=143770)
- Hydrocharitaceae - [urn:lsid:marinespecies.org:taxname:143751](https://www.marinespecies.org/aphia.php?p=taxdetails&id=143751)
- Cymodoceaceae - [urn:lsid:marinespecies.org:taxname:143768](https://www.marinespecies.org/aphia.php?p=taxdetails&id=143768)

**Sea turtles**
- Chelonioidea - [urn:lsid:marinespecies.org:taxname:987094](https://www.marinespecies.org/aphia.php?p=taxdetails&id=987094)

**Sea birds (this is partial and incomplete; this group is more involved for a variety of reasons)**
- Laridae (terns) - [urn:lsid:marinespecies.org:taxname:136988](https://www.marinespecies.org/aphia.php?p=taxdetails&id=136988)
- Diomedeidae (albatrosses) - [urn:lsid:marinespecies.org:taxname:148742](https://www.marinespecies.org/aphia.php?p=taxdetails&id=148742)
- Procellariidae - [urn:lsid:marinespecies.org:taxname:136998](https://www.marinespecies.org/aphia.php?p=taxdetails&id=136998)
- Spheniscidae (penguins) - [urn:lsid:marinespecies.org:taxname:196034](https://www.marinespecies.org/aphia.php?p=taxdetails&id=196034)

**Comment by MathewBiddle** [comment]
Zooplankton could be copepoda https://www.marinespecies.org/aphia.php?p=taxdetails&id=1080

**Comment by MathewBiddle** [comment]
Could worms help us do some of this filtering. Its constraints are marine, right?

**Comment by laurabrenskelle** [comment]
@MathewBiddle I discussed this with a colleague who studied marine invertebrates, and she basically said that zooplankton are "the animal component of the planktonic environment". Lots of animals across biological taxonomy have planktonic lifestyles for part or all of their lives. Apparently some copepods are planktonic, but [not all](https://www.marinespecies.org/copepoda/). I think it is basically the same idea for phytoplankton.

I think it will take more conversations with the observing communities who work with these organisms and the data because a taxonomic definition in the form of a list of AphiaIDs for these two groups may not be possible because it depends on the life stage of the organism in a lot of cases. It's an interesting problem. I wonder if plankton observations focus on particular taxa to make this easier? Or if it is just a measure of organisms per volume? Some questions for us to ask in the future.

**Comment by bbest** [comment]
Hi @laurabrenskelle and @MathewBiddle,

This is a great topic and I'd love to help out here. I'm noticing this interesting listing here in the OBIS manual:

[8 Dataset Examples: ENV-DATA | The OBIS manual](https://manual.obis.org/examples.html)
> **Contents**
> - [Fish abundance & distribution](https://manual.obis.org/examples.html#fish-abundance-and-distribution)
> - [Hard coral cover & composition](https://manual.obis.org/examples.html#hard-coral-cover-and-composition)
> - [Invertebrates abundance & distribution](https://manual.obis.org/examples.html#invertebrates-abundance-and-distribution)
> - [Macroalgae canopy cover & composition](https://manual.obis.org/examples.html#macroalgae-canopy-cover-and-composition)
> - [Mangroves cover & composition](https://manual.obis.org/examples.html#mangroves-cover-and-composition)
> - [Marine birds abundance & distribution](https://manual.obis.org/examples.html#marine-birds-abundance-and-distribution)
> - [Marine mammals abundance & distribution](https://manual.obis.org/examples.html#marine-mammals-abundance-and-distribution)
> - [Marine turtles abundance & distribution](https://manual.obis.org/examples.html#marine-turtles-abundance-and-distribution)
>   - [Survey & sighting data](https://manual.obis.org/examples.html#survey-and-sighting-data)
> - [Microbes biomass & diversity](https://manual.obis.org/examples.html#microbes-biomass-and-diversity)
> - [Phytoplankton biomass & diversity](https://manual.obis.org/examples.html#phytoplankton-biomass-and-diversity)
> - [Seagrass cover & composition](https://manual.obis.org/examples.html#seagrass-cover-and-composition)
> - [Zooplankton biomass & diversity](https://manual.obis.org/examples.html#zooplankton-biomass-and-diversity)
>
> **Special data types**:
>
> - [DNA derived data](https://manual.obis.org/dna_data.html)
>   - [eDNA data from Monterey Bay, California](https://manual.obis.org/dna_data.html#edna-data-from-monterey-bay-california)
>   - [16S rRNA gene metabarcoding data of Pico- to Mesoplankton](https://manual.obis.org/dna_data#s-rrna-gene-metabarcoding-data-of-pico--to-mesoplankton)
> - [Acoustic, imaging, or other multimedia data](https://manual.obis.org/other_data_types.html#multimedia-data)
> - [Tracking data](https://manual.obis.org/other_data_types.html#tracking-data.html)
> - [Habitat](https://manual.obis.org/other_data_types.html#habitat-data)


The example for [Zooplankton biomass & diversity](https://manual.obis.org/examples.html#zooplankton-biomass-and-diversity) limits itself to a [ZooScan dataset](https://obis.org/dataset/afa5b0e8-826d-4433-b698-beb176ef7880) and references [Best practices and recommendations for plankton imaging data management: Ensuring effective data flow towards European data infrastructures. Version 1.](https://repository.oceanbestpractices.org/handle/11329/1917), which does reference **Biological entity life stage** necessary to differentiate adult from larval zooplankton stages of species like crabs:

> - **measurementValueID**: Use collections SeaVoX Device Catalogue [L22](http://vocab.nerc.ac.uk/collection/L22/current/) and Biological entity life stage terms [S11](http://vocab.nerc.ac.uk/collection/S11/current/)

**Comment by MathewBiddle** [comment]
add the final list as a checklist to https://www.checklistbank.org/

**Comment by laurabrenskelle** [comment]
Once these lists reach a community consensus, it could be interesting to approach the developers of [robis](https://github.com/iobis/robis/) or other occurrence-grabbing programming packages to see if they could build in these queries to allow users to easily query for the most up-to-date OBIS occurrences for these taxonomic groups with a simple function.

**Comment by MathewBiddle** [comment]
@laurabrenskelle can you take a look at what it means to create and maintain a checklist at https://www.checklistbank.org/?

It would be nice to have an authoritative resource we can support and evolve over time.

**Comment by laurabrenskelle** [comment]
I added files for fish, hard corals, marine mammals, sea turtles, and seagrasses. The fish definitions are relying on the scope of OBIS/WoRMS to "filter" the data for marine species only.

**Comment by MathewBiddle** [comment]
That seems like a reasonable approach for now. I'd say go ahead and do the same for birds. If folks don't like it we can make it better with their contributions.

Feel free to send in another PR for birds and set it to close this issue. I think we have a good starting point to build something on top of.

**Comment by MathewBiddle** [comment]
The lists can now be found at https://github.com/ioos/marine_life_data_network/tree/main/eov_taxonomy

**Comment by laurabrenskelle** [comment]
https://github.com/iodepo/odis-arch/issues/465
