### ISSUE TITLE
[New Task]: Draft Marine Life Data Network Vision/Requirements Document

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/marine_life_data_network#8]
### Who is requesting this?

IOOS Regional Associations

### What is being requested?

A clear description as to what IOOS' requirements are for Marine Life observations. Ideally this would update the content at https://ioos.noaa.gov/data/data-standards/data-publishing/. However, the content might be more verbose than what we can/should add on the website. 

### What is the timeline for the completion of this task?

End of FY23 (September 2024)

### Provide a description or any other important information.

What are our NOAA requirements? What are our IOOS requirements? What are our user requirements?

I've started drafting content in a document which should be migrated to a markdown file here. We need to be clear that the content is super duper draft, however.

**Comment by MathewBiddle** [comment]
The document should include references to other activities and potential avenues for data sharing/engagement. Under **Who?** add this list with roles (data user, data generator, resource manager/application).
* SoundCoop
* eDNA WG
* PACM - passive acoustic cetacean monitoring
* HAB groups - NHABON
* CEFI - Climate Ecosystem Fisheries Initiative
* Ecosystem Modeling Groups
* Species Distribution Modeling groups
* RWSC - wind community

To-Do:
* Collect list of requirements. Where do we get those? @GabCan ?
  * national & international (eg. GOOS)
* How do we get to indicators??

**Comment by laurabrenskelle** [comment]
I tweaked the Vision section in the [readme](https://github.com/ioos/marine_life_data_network/blob/main/README.md) and I added contributors & stakeholders to the Who section.

Re: eDNA WG - Do we mean the MBON eDNA WG? NOAA Omics group?

Another big picture question - is the vision for MLDN to be the aggregator only for the IOOS data enterprise, or is it ideally for all NOAA ML data? And if that's not IOOS, who is that cross-NOAA source?

**Comment by laurabrenskelle** [comment]
Re: My big picture question from yesterday -  a European parallel organization/effort: https://emodnet.ec.europa.eu/en/biology

**Comment by MathewBiddle** [comment]
Recreating the BIO-ICE data flow diagram for Marine Life data. This is a high level view of where data should flow.

```mermaid

%%{
  init: {
    'theme': 'base',
    'themeVariables': {
      'primaryColor': '#007396',
      'primaryTextColor': '#fff',
      'primaryBorderColor': '#003087',
      'lineColor': '#003087',
      'secondaryColor': '#007396',
      'tertiaryColor': '#CCD1D1'
    },
   'flowchart': { 'curve': 'basis' }
  }
}%%

flowchart LR

A["Marine Life data 
& 
metadata"] 

B[("Raw Data 
Access Point
(eg. RA ERDDAP)")]

C{{"Darwin Core
Alignment"}}

D[(NCEI)]

E[("OBIS node")]

G([OBIS])

H([GBIF])

I[("IOOS Data Catalog
(data.ioos.us)")]

FC(["Federal Catalogs/
Products"])


A --> B
B -- If using IOOS RA ERDDAP --> I
B --> C
B --> D
%% E --> D

C --> E
E --> G
E --> H

I --> FC

G --> FC
H --> FC


D --> FC
```

**Comment by MathewBiddle** [comment]
After the Marine Life in-person meeting, we discovered that most of the documentation has already been written in the `mbon-docs` repository. So, we have a plan:

- [ ] @MathewBiddle port mbon-docs to this repo in `gh-pages`
- [ ] @laurabrenskelle update the content to reflect MDLN
- [ ] @conniekot review updates
- [ ] @GabCan review updates

**Comment by MathewBiddle** [comment]
@laurabrenskelle I have copied the `mbon-docs` website material over here under the `gh-pages` branch. 

* source content: https://github.com/ioos/marine_life_data_network/tree/gh-pages
* webpage: https://ioos.github.io/marine_life_data_network/

The website will need to be updated to adjust most of the MBON references to Marine Life. We also need to fiddle with the configurations to ensure all the dynamic links are pointing to the correct repository for this documentation page. For example, "Edit me" still goes to the `mbon-docs` GitHub repository, not to the `marine_life_data_network`. Those are mostly changes to the [configuration file](https://github.com/ioos/marine_life_data_network/blob/gh-pages/_config.yml). 

If you don't mind taking a crack at updating the content, that would be much appreciated. If you get stuck along the way, please reach out.

**Comment by MathewBiddle** [comment]
I'm fiddling with the data flow diagram to address some comments from our Marine Life Team tag up in Silver Spring. One of the comments was about linking to environmental data in the flow diagram. 

While I agree with the comment, it proved to be a little tricky adding in that additional node and then it got me thinking. Do we need to highlight that? Or can the diagram end with the various access points, which then are available for people to integrate with the already available IOOS endpoints for environmental data? 

So, I've drafted a slight change to the data flow diagram to remove the last node for "Federal Catalogs/Products/Integration w/ environmental Obs" and adjust some of the shapes. The shapes now play an important role in highlighting where the data access points are in the process.

```mermaid
%%{
  init: {
    'theme': 'base',
    'themeVariables': {
      'primaryColor': '#007396',
      'primaryTextColor': '#fff',
      'primaryBorderColor': '#003087',
      'lineColor': '#003087',
      'secondaryColor': '#007396',
      'tertiaryColor': '#CCD1D1'
    },
   'flowchart': { 'curve': 'basis' }
  }
}%%

flowchart LR

A["Marine Life data 
& 
metadata"] 

B[("Raw Data 
Access Point
(eg. RA ERDDAP)")]

C("Darwin Core
Alignment")

D[("NOAA's National Centers
for Environmental Information (NCEI)")]

E[("Ocean Biodiversity
Information System 
node")]

G[("Ocean Biodiversity
Information System (OBIS)")]

H[("Global Biodiversity Information Facility (GBIF)")]

I[("IOOS Data Catalog
(data.ioos.us)")]

A --> B
B --- Metadata ---> I
B --> C
B ----> D



C --> E
E --> G
E --> H
```

**Comment by laurabrenskelle** [comment]
The only thing that I find unclear is the "metadata" box that then goes to the IOOS Data Catalog. Would writing "metadata only" underneath "IOOS Data Catalog" in that box be more clear, similar to how the first box explicitly says "data and metadata"? My understanding is that there's no intermediate step between ERDDAP and the catalog, it is just harvesting metadata from ERDDAP to build the catalog, right?

**Comment by MathewBiddle** [comment]
I agree. How about this?

```mermaid
%%{
  init: {
    'theme': 'base',
    'themeVariables': {
      'primaryColor': '#007396',
      'primaryTextColor': '#fff',
      'primaryBorderColor': '#003087',
      'lineColor': '#003087',
      'secondaryColor': '#007396',
      'tertiaryColor': '#CCD1D1'
    },
   'flowchart': { 'curve': 'basis' }
  }
}%%

flowchart LR

A["Marine Life data 
& 
metadata"] 

B[("Raw Data 
Access Point
(eg. RA ERDDAP)")]

C("Darwin Core
Alignment")

D[("NOAA's National Centers
for Environmental Information (NCEI)")]

E[("Ocean Biodiversity
Information System 
node")]

G[("Ocean Biodiversity
Information System (OBIS)")]

H[("Global Biodiversity Information Facility (GBIF)")]

I[("IOOS Data Catalog
(data.ioos.us)
(metadata only)")]

A --> B
B ----> I
B --> C
B ----> D



C --> E
E --> G
E --> H
E -- OBIS-USA --> D
```

**Comment by MathewBiddle** [comment]
I want to highlight where there are automated processes to move data from place to place. So, I've made the automated parts of the process as bold arrows. 

I'm wondering if this conveys my thoughts more clearly or if it should be the opposite way, with bold lines signifying when it is a manual process?

```mermaid
%%{
  init: {
    'theme': 'base',
    'themeVariables': {
      'primaryColor': '#007396',
      'primaryTextColor': '#fff',
      'primaryBorderColor': '#003087',
      'lineColor': '#003087',
      'secondaryColor': '#007396',
      'tertiaryColor': '#CCD1D1'
    },
   'flowchart': { 'curve': 'basis' }
  }
}%%

flowchart LR

A["Marine Life data 
& 
metadata"] 

B[("Raw Data 
Access Point
(eg. RA ERDDAP)")]

C("Darwin Core
Alignment")

D[("NOAA's National Centers
for Environmental Information (NCEI)")]

E[("Ocean Biodiversity
Information System 
node")]

G[("Ocean Biodiversity
Information System (OBIS)")]

H[("Global Biodiversity Information Facility (GBIF)")]

I[("IOOS Data Catalog
(data.ioos.us)
(metadata only)")]

A --> B
B ====> I
B --> C
B ----> D



C --> E
E ==> G
E ==> H
E == OBIS-USA ==> D
```

**Comment by laurabrenskelle** [comment]
I could see it either way. I think if there is a key that denotes what the bold lines mean, that would be clear enough.

**Comment by MathewBiddle** [comment]
I switched it and went with dotted lines for manual processes:

```mermaid
%%{
  init: {
    'theme': 'base',
    'themeVariables': {
      'primaryColor': '#007396',
      'primaryTextColor': '#fff',
      'primaryBorderColor': '#003087',
      'lineColor': '#003087',
      'secondaryColor': '#007396',
      'tertiaryColor': '#CCD1D1'
    },
   'flowchart': { 'curve': 'basis' }
  }
}%%

flowchart LR

A["Marine Life data 
& 
metadata"] 

B[("Raw Data 
Access Point
(eg. RA ERDDAP)")]

C("Darwin Core
Alignment")

D[("NOAA's National Centers
for Environmental Information (NCEI)")]

E[("Ocean Biodiversity
Information System 
node")]

G[("Ocean Biodiversity
Information System (OBIS)")]

H[("Global Biodiversity Information Facility (GBIF)")]

I[("IOOS Data Catalog
(data.ioos.us)
(metadata only)")]

A -.-> B
B ----> I
B -.-> C
B -..-> D



C -.-> E
E --> G
E --> H
E -- OBIS-USA --> D
```

**Comment by sformel-usgs** [comment]
I don't see any red flags with this diagram. If I wasn't already involved with Marine Life, my big question would be, "What is upstream of the Marine Life node in this diagram?"  It might be worth including data.gov in here to make it clear that you're solving that requirement too.

Here is a suggested revision that might be easier to read:

```mermaid

%%{
  init: {
    'theme': 'base',
    'themeVariables': {
      'primaryColor': '#007396',
      'primaryTextColor': '#fff',
      'primaryBorderColor': '#003087',
      'lineColor': '#003087',
      'secondaryColor': '#007396',
      'tertiaryColor': '#CCD1D1'
    },
   'flowchart': { 'curve': 'basis'
    }
}
}%%

flowchart TD

A["Marine Life 
data & metadata"] 

B[("Raw Data 
Access Point
(eg. RA ERDDAP)")]

D[("NOAA's National Centers for Environmental Information (NCEI)")]

E("OBIS-USA Node")

G[("Ocean Biodiversity Information System (OBIS)")]

H[("Global Biodiversity Information Facility (GBIF)")]

I[("IOOS Data Catalog
(data.ioos.us)")]

J[("Data.gov")]

A --> B -->|"Darwin Core Alignment"| E
B-->|"Metadata"| I
D & I-->|"Metadata"| J 

E ==> G
E ==> H
E ==> D

```

**Comment by MathewBiddle** [comment]
@sformel-usgs thanks for reviewing and providing something to iterate on. I agree with your comment. I removed those endpoints because it gets really messy if we start pointing at all the potential "slurpers". So, I ended up adding a description to the website to highlight those parts https://ioos.github.io/marine_life_data_network/data-flow.html

**Comment by MathewBiddle** [comment]
@GabCan released this to the world! We can now say this is complete. Closing. 

> ---------- Forwarded message ---------
> From: Gabrielle Canonico - NOAA Federal <gabrielle.canonico@noaa.gov>
> Date: Mon, Sep 16, 2024 at 1:20 PM
> Subject: IOOS Marine Life Data Network Guidance
> 
> 
> Dear IOOS Community,
> 
> The IOOS Marine Life team has developed comprehensive documentation of recommended best practices for managing marine life data. We have published these recommendations to the Marine Life Data Network website: https://ioos.github.io/marine_life_data_network/. The goal of the IOOS Marine Life Data Network (MLDN) is to ensure that all marine life data generated by IOOS Regional Associations and related networks, such as MBON and ATN, are openly accessible, well documented, and ready for reuse. The documentation provided was originally developed through the work of the Marine Biodiversity Observation Network’s DMAC Working Group and is now being expanded to cover all IOOS marine life data. The documentation provides the IOOS DMAC guidelines for marine life data management to help us achieve these goals for open and FAIR data.
> 
> Please review the Marine Life Data Network website and consider how these best practices might be integrated into our current processes and strategies. The Marine Life Data Network is an open, collaborative effort with the entire IOOS community. We welcome feedback on the website and data management recommendations through the [GitHub repository](https://github.com/ioos/marine_life_data_network/tree/gh-pages) where the content is managed.
> 
> Best regards,
> 
> Gabrielle

**Comment by conniekot** [comment]
@MathewBiddle Can you please change this Status = Done? I can't do that - thanks!

**Comment by MathewBiddle** [comment]
Initially, I wanted to wait until during our monthly tag-up with Axiom to physically move issues to `Done`. So that was can all be on the same page. But, now I'm realizing that will slow progress. New guidance should be to add a description as to why a card is moved between status'.

 As the guidance has been released to the world, this issue has been moved to `Done`. Congrats 🎉
