### ISSUE TITLE
New Task: Begin operationally submitting non-embargoed deployments to NCEI

### ISSUE THREAD

**Issue by laurabrenskelle** [ioos/marine_life_data_network#80]
### Who is requesting this?

@ioos/marine-life

### What is being requested?

Non-embargoed trajectory datasets are submitted via ADR to NCEI WAF for archive.

Additionally: "5.1.5 Create automated service within ATN DAC Reg App for grouping deployments into synthetic 'projects' and connecting metadata returned from NCEI for access by PIs."

### What indicates this is done (i.e., how do we know this is complete)?

Non-embargoed trajectory datasets are automatically submitted via ADR to the NCEI WAF for archiving.

### Provide a description or any other important information.

This is from two different Marine Life Data Network Trello cards combined into one.

**Comment by MathewBiddle** [comment]
related:
* #41

**Comment by MathewBiddle** [comment]
duplicate of https://github.com/ioos/marine_life_data_network/issues/41
